name: Continuous Integration

on:
  push:
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize
  #     - ready_for_review
  #     - edited

jobs:
  verify:
    name: Verify jips
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Verify jips
        run: |
          cd site
          yarn
          yarn validate

  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@2391250ab05295bddd51e36a8c6295edb6343b0e
        with:
          check_filenames: true
          ignore_words_file: config/.codespell-whitelist
          skip: ./site,./.git,LICENSE

  markdownlint:
    name: MarkdownLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          globs: "**/jip-*/jip.md"
